version: '3.7'
services:
    postgres:
        image: postgres:9.6
        env_file: 
            - ./airflow.env
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - ./pgdata:/var/lib/postgresql/data/pgdata
            - ./external_data:/var/lib/postgresql/data/external
        ports:
            - "5432:5432"
        logging:
            options:
                max-size: 10m
                max-file: "3"

    webserver:
        build: .
        restart: always
        depends_on:
            - postgres
        env_file: 
            - ./airflow.env
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./plugins:/usr/local/airflow/plugins
            - ./notebooks:/usr/local/airflow/notebooks
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3